"use client";
import {useState} from 'react';
import {api} from '../../lib/api';
type Control={version:number;enforced:boolean;budgets:Record<string,{committed_minutes:number;actual_minutes:number;approved_minutes:number|null;remaining_minutes:number|null}>;issues:{reason:string;task?:number;person?:number;day?:string;service?:number;minutes?:number;bucket?:string}[]};
const reasons:Record<string,string>={missing_reservations:'Tarea sin reservas completas',calendar:'Calendario no confirmado o día no laborable',assignment:'Nombramiento requiere revisión',unconfirmed_capacity:'Capacidad sin aprobar',over_capacity:'Reservas exceden disponibilidad',budget_exceeded:'Presupuesto excedido'};
export default function PlanningControl({institution}:{institution:string}){
 const [data,setData]=useState<Control>(),[base,setBase]=useState(''),[reserve,setReserve]=useState(''),[enforced,setEnforced]=useState(false),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){const value=await api<Control>(`capacity/institutions/${institution}/planning/`);setData(value);setBase(String(value.budgets.base.approved_minutes??''));setReserve(String(value.budgets.reserve.approved_minutes??''));setEnforced(value.enforced);}
 return <section aria-label="Control institucional de planificación"><h2>Presupuesto y reservas de tareas</h2><p>Dirección confirma los presupuestos en minutos. Las 295 h base y 59 h de reserva son referencias provisionales, no valores aprobados automáticamente. El control obligatorio exige reservas completas al aprobar nuevas líneas base. Antes de activarlo, regularice las tareas abiertas.</p><button disabled={busy} onClick={async()=>{setBusy(true);setNotice('');try{await load();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}>Consultar presupuesto y conflictos</button>{notice&&<p role="status">{notice}</p>}{data&&<><p>Control obligatorio: {data.enforced?'Activo':'Pendiente de activación'} · Versión {data.version}</p>{Object.entries(data.budgets).map(([bucket,b])=><p key={bucket}>{bucket==='base'?'Base':'Reserva'}: comprometidos {b.committed_minutes} min · reales {b.actual_minutes} min · aprobados {b.approved_minutes??'Sin confirmar'} min · saldo disponible {b.remaining_minutes??'Sin confirmar'} min.</p>)}<ul>{data.issues.map((i,n)=><li key={n}>{reasons[i.reason]??i.reason} {i.task&&`· Tarea ${i.task}`} {i.person&&`· Persona ${i.person}`} {i.day&&`· ${i.day}`} {i.service&&`· Servicio ${i.service}`} {i.minutes!==undefined&&`· ${i.minutes} min`} {i.bucket&&`· ${i.bucket==='base'?'Base':'Reserva'}`}</li>)}</ul>{!data.issues.length&&<p>No hay conflictos detectados con las reservas actuales. Si el control está inactivo, esto no acredita reservas completas.</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setNotice('');try{await api(`capacity/institutions/${institution}/planning/`,'POST',{version:data.version,enforced,base_minutes:Number(base),reserve_minutes:Number(reserve),rationale:reason});await load();setNotice('Control institucional guardado y auditado.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}><label>Presupuesto base en minutos<input type="number" required min={0} value={base} onChange={e=>setBase(e.target.value)}/></label><label>Presupuesto de reserva en minutos<input type="number" required min={0} value={reserve} onChange={e=>setReserve(e.target.value)}/></label><label><input type="checkbox" checked={enforced} onChange={e=>setEnforced(e.target.checked)}/>Exigir reservas completas en aprobación</label><label>Fundamento del control<textarea required maxLength={3000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()}>Confirmar control de planificación</button></form></>}</section>;
}
