import Link from "next/link";
import InstitutionalDirectory from "../../components/InstitutionalDirectory";
import Image from "next/image";
import { services } from "./data";
export default function PortalHome() { return <main className="portal-main">
  <section className="portal-hero"><div className="portal-hero-copy"><span className="portal-eyebrow">ESCUELAS DE SALUD Y ODONTOLOGÍA · UNIVERSIDAD MODELO</span><h1>Tu bienestar tiene un lugar aquí.</h1><p>Conoce nuestros servicios de salud. Elige el que necesitas, envía tu solicitud y consulta la respuesta desde tu cuenta.</p><div className="portal-actions"><Link className="portal-button" href="#servicios">Explorar servicios <span aria-hidden>→</span></Link><Link className="portal-text-link" href="/portal/cuenta">Consultar mi solicitud</Link></div><div className="portal-hero-note">La fecha de atención se confirma por el servicio; enviar una solicitud no reserva un horario.</div></div><div className="portal-hero-image"><Image src="/images/salud-hero.png" alt="Profesionales de salud en atención odontológica y fisioterapia" fill priority sizes="(max-width: 800px) 100vw, 50vw" /></div></section>
  <section className="portal-section" id="servicios"><div className="portal-section-heading"><span className="portal-eyebrow">A TU ALCANCE</span><h2>¿Qué servicio necesitas?</h2><p>Puedes explorar cualquiera de las seis áreas. Al entrar a una, las demás siguen disponibles en las pestañas superiores.</p></div><div className="portal-cards">{services.map((s,i)=><Link key={s.slug} className="portal-card" href={`/portal/servicios/${s.slug}`}><span className={`portal-card-icon portal-color-${i}`} aria-hidden>{s.icon}</span><strong>{s.name}</strong><span>{s.summary}</span><span className="portal-card-more">Conocer el servicio <span aria-hidden>→</span></span></Link>)}</div></section>
  <InstitutionalDirectory compact />
  <section className="portal-steps"><div className="portal-section-heading"><span className="portal-eyebrow">ASÍ FUNCIONA</span><h2>Solicitar atención es sencillo</h2></div><div className="portal-step-grid"><div><b>01</b><h3>Elige un servicio</h3><p>Consulta las áreas y selecciona la que necesitas.</p></div><div><b>02</b><h3>Envía tu solicitud</h3><p>Crea tu cuenta y señala tu preferencia de sede y día.</p></div><div><b>03</b><h3>Consulta la respuesta</h3><p>El servicio revisa la disponibilidad y confirma o responde desde tu cuenta.</p></div></div></section>
</main> }
