"use client";
import {useState} from 'react';
import {api} from '../../lib/api';
type Comparison={calendar_confirmed:boolean;calendar_version:number;observed_at:string;issues:{task_id:number;title:string;reason:string}[];rows:{person_id:number;name:string;day:string;planned_minutes:number;allocated_minutes:number|null;overload_minutes:number|null;has_unavailability:boolean|null;status:string;tasks:{id:number;title:string;minutes:number}[]}[]};
const labels:Record<string,string>={assignment_review:'Nombramiento requiere revisión',unconfirmed:'Sin capacidad aprobada',overloaded:'Sobrecarga',within_capacity:'Dentro de capacidad'};
export default function TaskCapacity({service}:{service:number}){
 const [start,setStart]=useState('2026-10-01'),[data,setData]=useState<Comparison>(),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 return <section aria-label="Capacidad para tareas"><h2>Capacidad y ausencias en la planificación</h2><p>Compara tareas comprometidas abiertas con capacidad aprobada para este servicio. Reparte la estimación completa entre días laborales de sus fechas de línea base, según el calendario confirmado; no calcula trabajo restante ni reserva minutos. Las ausencias ya están descontadas en la distribución aprobada.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setNotice('');setData(undefined);try{setData(await api<Comparison>(`tracking/services/${service}/capacity/?start=${start}`));}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}}}><label>Inicio de semana para capacidad<input type="date" min="2026-10-01" required value={start} onChange={e=>{setStart(e.target.value);setData(undefined);}}/></label><button disabled={busy}>Comparar tareas con capacidad</button></form>{notice&&<p role="status">{notice}</p>}{data&&<>{!data.calendar_confirmed?<p>Confirme el calendario institucional para calcular la carga diaria.</p>:<><p>Calendario versión {data.calendar_version}. Consulta del {new Date(data.observed_at).toLocaleString('es-MX')}. Actualice después de aprobar cambios de tareas, capacidad o ausencias.</p>{data.issues.map(i=><p key={i.task_id}>Tarea {i.task_id}: {i.title} · {i.reason==='no_workdays'?'Sin días laborales en su intervalo':'Sin estimación de minutos'}.</p>)}{!data.rows.length&&<p>No hay carga estimada distribuible en estos siete días.</p>}<ul>{data.rows.map(r=><li key={`${r.person_id}-${r.day}`}><strong>{r.name} · {r.day}: {labels[r.status]}</strong><p>Carga estimada: {r.planned_minutes} min · Asignación aprobada al servicio: {r.allocated_minutes??'Sin confirmar'} min{r.overload_minutes!==null&&` · Exceso: ${r.overload_minutes} min`}{r.has_unavailability&&' · Con indisponibilidad aprobada ese día'}</p><ul>{r.tasks.map(t=><li key={t.id}>Tarea {t.id}: {t.title} · {t.minutes} min</li>)}</ul></li>)}</ul></>}</>}</section>;
}
