"use client";
import {useState} from 'react';
import {api} from '../../lib/api';
import {AdministrativeTimeForm} from './AdministrativeTime';
import TimeCorrection from './TimeCorrection';
type Fields={title:string;starts:string;due:string;owner:number;estimated_minutes:number;budget_bucket?:string;reservation_plan?:{person:number;day:string;minutes:number}[]};
type Row={id:number;budget_bucket?:string;actor__username?:string;requested_by__username?:string;reviewed_by__username?:string;note?:string;rationale?:string;review_reason?:string;state?:string;created_at:string;day?:string;entry_id?:number;version?:number;minutes:number;effective_minutes:number;correction_version:number;can_correct?:boolean;can_request_correction?:boolean;proposal?:Fields;previous?:Fields};
type Page={results:Row[];next_before:number|null};
function baseline(value:Fields){return <p>{value.title} · {value.starts} a {value.due} · Responsable {value.owner} · {value.estimated_minutes} min · {value.budget_bucket==='reserve'?'Reserva':'Base'}. {(value.reservation_plan??[]).map(r=>`${r.day}: persona ${r.person}, ${r.minutes} min`).join('; ')}</p>;}
export default function TaskHistory({task}:{task:number}){
 const [kind,setKind]=useState('events'),[rows,setRows]=useState<Row[]>([]),[next,setNext]=useState<number|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(before?:number){setBusy(true);setNotice('');try{const result=await api<Page>(`tracking/tasks/${task}/history/?kind=${kind}${before?`&before=${before}`:''}`);setRows(old=>before?[...old,...result.results.filter(r=>!old.some(p=>p.id===r.id))]:result.results);setNext(result.next_before);}catch(e){setNotice((e as Error).message);setRows([]);setNext(null);}finally{setBusy(false);}}
 return <section aria-label="Historial completo de tarea"><h3>Historial completo</h3><label>Tipo de historial<select disabled={busy} value={kind} onChange={e=>{setKind(e.target.value);setRows([]);setNext(null);}}><option value="events">Actividad</option><option value="changes">Línea base</option><option value="time">Horas originales y efectivas</option><option value="corrections">Ajustes de horas</option></select></label><button disabled={busy} onClick={()=>void load()}>Consultar historial completo</button>{notice&&<p role="status">{notice}</p>}{rows.map(r=><article key={r.id}><p>Registro {r.id} · {new Date(r.created_at).toLocaleString('es-MX')} · {r.actor__username??r.requested_by__username} {r.state&&`· ${r.state}`}</p><p>{r.note??r.rationale}</p>{kind==='time'&&<p>{r.day} · Original: {r.minutes} min · Efectivo: {r.effective_minutes} min · {r.budget_bucket==='reserve'?'Reserva institucional':'Base'}</p>}{kind==='corrections'&&<p>Entrada {r.entry_id} · Ajuste {r.version} · {r.minutes} min</p>}{r.previous&&<><h4>Antes de la propuesta</h4>{baseline(r.previous)}</>}{r.proposal&&<><h4>Propuesta</h4>{baseline(r.proposal)}<p>Revisión: {r.reviewed_by__username??'Pendiente'} · {r.review_reason}</p></>}{kind==='time'&&r.can_request_correction&&<AdministrativeTimeForm key={`admin-${r.id}-${r.correction_version}`} entry={r} onSaved={()=>load()}/>}
{kind==='time'&&r.can_correct&&<TimeCorrection entry={r} onSaved={()=>load()}/>}</article>)}{next!==null&&<button disabled={busy} onClick={()=>void load(next)}>Cargar más historial</button>}</section>;
}
