"use client";
import {useState} from 'react';
import {api} from '../../lib/api';
type Data={version:number;current:number;targets:{id:number;version:number;text:string;locator:string}[];changes:{from_text:string;to_text:string;from_locator:string;to_locator:string;id:number;state:string;source_from:number;source_to:number;rationale:string;review_reason:string}[]};
export default function SourceChanges({instance,onChange}:{instance:number;onChange:()=>Promise<void>}){
 const [data,setData]=useState<Data>(),[target,setTarget]=useState(''),[reason,setReason]=useState(''),[review,setReview]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setData(await api<Data>(`questionnaires/${instance}/source-changes/`));}
 async function run(action:()=>Promise<void>){setBusy(true);setNotice('');try{await action();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 return <section aria-label="Cambio de fuente"><h3>Cambio de versión de fuente</h3><p>Requiere propuesta y revisión de otra persona de Dirección. Al aprobar, retira la publicación y validación actual; conserva las fuentes, ayudas y respuestas anteriores. Deben prepararse y revisarse la ayuda y respuesta para la nueva fuente.</p><button disabled={busy} onClick={()=>void run(load)}>Consultar cambios de fuente (Dirección)</button>{notice&&<p role="status">{notice}</p>}{data&&<><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api(`questionnaires/${instance}/source-changes/`,'POST',{version:data.version,target:Number(target),rationale:reason});await load();setNotice('Cambio de fuente propuesto; pendiente de revisión independiente.');});}}><label>Nueva versión de fuente<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Seleccione…</option>{data.targets.map(t=><option key={t.id} value={t.id}>Versión {t.version}: {t.text}</option>)}</select></label>{data.targets.filter(t=>String(t.id)===target).map(t=><p key={t.id}>{t.text} · {t.locator}</p>)}<label>Motivo del cambio de fuente<textarea required maxLength={3000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!target||!reason.trim()}>Proponer cambio de fuente</button></form><label>Fundamento de revisión de fuente<textarea maxLength={3000} value={review} onChange={e=>setReview(e.target.value)}/></label>{data.changes.map(c=><article key={c.id}><p>Cambio {c.id}: fuente {c.source_from} → {c.source_to} · {c.state} · {c.rationale}</p><p>Fuente anterior: {c.from_text} · {c.from_locator}</p><p>Fuente propuesta: {c.to_text} · {c.to_locator}</p><p>{c.review_reason}</p>{c.state==='pending'&&[true,false].map(approve=><button key={String(approve)} disabled={busy||!review.trim()} onClick={()=>void run(async()=>{await api(`source-changes/${c.id}/review/`,'POST',{approve,rationale:review});await load();await onChange();setNotice(approve?'Fuente actualizada; publicación y validación retiradas.':'Cambio rechazado; fuente conservada.');})}>{approve?'Aprobar':'Rechazar'} cambio de fuente {c.id}</button>)}</article>)}</>}</section>;
}
