"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {api,listApi,setCsrf} from "../../lib/api";
import "../academico/academic.css";
import "./cash.css";
type Service={id:number;name:string;school_name:string;can_manage:boolean};
type Person={id:number;name:string;username:string};
type Shift={id:number;service:number;service_name:string;school_name:string;responsible_name:string;assigned_by:string;label:string;starts:string;ends:string;state:string;revision:number;opening:string|null;balance:string;counted:string|null;expected:string|null;difference:string|null;close_reason:string;can_operate:boolean;can_manage:boolean};
type Movement={id:number;folio:string;kind:string;amount:string;concept:string;reference:string;related:number|null;actor:string;created_at:string};
type Page<T>={results:T[];count:number};
type Summary={totals:Record<string,string>;open_shifts:number;closed_shifts:number;differences:string;with_difference:number;cash_in_open_shifts:string;basis:string};
const states:Record<string,string>={planned:"Programado",open:"Abierto",closed:"Cerrado",cancelled:"Cancelado"};
const kinds:Record<string,string>={collection:"Cobro",fund_in:"Ingreso de fondo",withdrawal:"Retiro / entrega",refund:"Devolución"};
const money=(s:string|null|undefined)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(s||0));
const date=(s:string)=>new Date(s).toLocaleString("es-MX");
export default function CashPage(){
 const [services,setServices]=useState<Service[]>([]),[service,setService]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[state,setState]=useState(""),[page,setPage]=useState(1);
 const [rows,setRows]=useState<Page<Shift>>({results:[],count:0}),[summary,setSummary]=useState<Summary>(),[people,setPeople]=useState<Person[]>([]);
 const [selected,setSelected]=useState<Shift>(),[movements,setMovements]=useState<Page<Movement>>({results:[],count:0}),[mpage,setMpage]=useState(1);
 const [error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[kind,setKind]=useState("collection");
 const revision=useRef(0),detailRevision=useRef(0),shiftKey=useRef(""),movementKey=useRef("");
 const own=services.find(s=>String(s.id)===service);
 const query=()=>new URLSearchParams({...service?{service}:{},...from?{date_from:from}:{},...to?{date_to:to}:{},...state?{state}:{}}).toString();
 async function refresh(){const rev=++revision.current;const q=query();const [r,s]=await Promise.all([api<Page<Shift>>(`cash/shifts/?${q}&page=${page}`),api<Summary>(`cash/summary/?${q}`)]);if(rev===revision.current){setRows(r);setSummary(s);}}
 async function open(id:number,p=1){const rev=++detailRevision.current;setSelected(undefined);setMovements({results:[],count:0});const [s,m]=await Promise.all([api<Shift>(`cash/shifts/${id}/`),api<Page<Movement>>(`cash/shifts/${id}/movements/?page=${p}`)]);if(rev===detailRevision.current){setSelected(s);setMovements(m);setMpage(p);}}
 useEffect(()=>{let live=true;(async()=>{const s=await api<{csrf:string;authenticated:boolean}>("session/");setCsrf(s.csrf);if(!s.authenticated)throw Error("Ingresa con tu cuenta del personal.");const r=await listApi<Service>("cash/services/");if(live){setServices(r);setReady(true);}})().catch(e=>setError(String(e)));return()=>{live=false;revision.current++;detailRevision.current++;};},[]);
 useEffect(()=>{if(!ready)return;setError("");refresh().catch(e=>setError(String(e)));return()=>{revision.current++;};},[ready,service,from,to,state,page]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{let live=true;setPeople([]);setSelected(undefined);detailRevision.current++;if(own?.can_manage)listApi<Person>(`cash/services/${service}/responsibles/`).then(r=>{if(live)setPeople(r);}).catch(e=>setError(String(e)));return()=>{live=false;};},[service,own?.can_manage]);
 async function submit(e:FormEvent<HTMLFormElement>,mode:string){e.preventDefault();const form=e.currentTarget;const v=Object.fromEntries(new FormData(form));setBusy(true);setError("");setMessage("");try{
  if(mode==="assign"){
   if(!shiftKey.current)shiftKey.current=crypto.randomUUID();
   await api("cash/shifts/","POST",{service:Number(service),responsible:Number(v.responsible),label:v.label,starts:new Date(String(v.starts)).toISOString(),ends:new Date(String(v.ends)).toISOString(),client_key:shiftKey.current});shiftKey.current="";
  }else if(selected){
   if(mode==="movement"){
    if(!movementKey.current)movementKey.current=crypto.randomUUID();
    await api(`cash/shifts/${selected.id}/movements/`,"POST",{kind,amount:v.amount,concept:v.concept,reference:v.reference,related:kind==="refund"?Number(v.related):null,revision:selected.revision,client_key:movementKey.current});movementKey.current="";
   }else await api(`cash/shifts/${selected.id}/`,"POST",{action:mode,revision:selected.revision,...mode!=="cancel"?{amount:v.amount}:{},reason:v.reason||""});
   await open(selected.id);
  }
  form.reset();await refresh();setMessage("Registro guardado. El historial de caja se conserva.");
 }catch(e){setError(String(e));}finally{setBusy(false);}}
 return <><header className="topbar"><Link href="/personal">Inicio del personal</Link><h1>Caja por servicio</h1><Link href="/escuelas">Escuelas</Link></header><main className="cash-shell">
 <p>Efectivo · Pesos mexicanos (MXN). Cada responsable opera sus turnos; Dirección supervisa su escuela y la administración institucional consulta todas sus escuelas.</p>
 {error&&<div role="alert" className="error">{error} <button onClick={()=>{refresh().catch(e=>setError(String(e)));if(selected)open(selected.id).catch(e=>setError(String(e)));}}>Actualizar datos</button></div>}{message&&<p role="status">{message}</p>}
 <section className="panel cash-filters" aria-label="Filtros de caja"><label>Servicio<select aria-label="Servicio" value={service} disabled={busy} onChange={e=>{setService(e.target.value);setPage(1);}}><option value="">Todos los autorizados</option>{services.map(s=><option key={s.id} value={s.id}>{s.school_name} · {s.name}</option>)}</select></label><label>Desde (inicio del turno)<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label>Hasta<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label><label>Estado<select aria-label="Estado" value={state} onChange={e=>{setState(e.target.value);setPage(1);}}><option value="">Todos</option>{Object.entries(states).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></section>
 {summary&&<><section className="cash-metrics" aria-label="Monitoreo de efectivo">{[["Cobros",summary.totals.collection],["Devoluciones",summary.totals.refund],["Ingresos de fondo",summary.totals.fund_in],["Retiros / entregas",summary.totals.withdrawal],["Efectivo esperado en turnos abiertos",summary.cash_in_open_shifts],["Diferencia neta en cierres",summary.differences]].map(([label,value])=><div className="panel" key={label}><span>{label}</span><strong>{money(value)}</strong></div>)}</section><p>{summary.open_shifts} turnos abiertos · {summary.closed_shifts} cerrados · {summary.with_difference} cierres con diferencia. {summary.basis}</p></>}
 {own?.can_manage&&<details className="panel"><summary>Asignar turno y responsable</summary><form onSubmit={e=>submit(e,"assign")} onChange={()=>{shiftKey.current="";}}><fieldset disabled={busy}><label>Nombre del turno<input name="label" maxLength={100} required placeholder="Ej. Matutino"/></label><label>Responsable<select aria-label="Responsable" name="responsible" required><option value="">Seleccionar colaborador</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.username}</option>)}</select></label><label>Inicio<input type="datetime-local" name="starts" required/></label><label>Fin<input type="datetime-local" name="ends" required/></label><p>Horario local de este dispositivo. El responsable abre dentro de este horario. Para cambiarlo, cancela el turno sin abrir y registra otro.</p><button>Asignar turno</button></fieldset></form></details>}
 <section className="panel"><h2>Turnos de caja</h2><p>{rows.count} registros. Selecciona un turno para operar o revisar sus movimientos.</p><div className="cash-scroll"><table><thead><tr><th>Servicio / escuela</th><th>Turno</th><th>Responsable</th><th>Estado</th><th>Efectivo esperado</th><th>Acción</th></tr></thead><tbody>{rows.results.map(s=><tr key={s.id}><td>{s.service_name}<small>{s.school_name}</small></td><td>{s.label}<small>{date(s.starts)} — {date(s.ends)}</small></td><td>{s.responsible_name}</td><td>{states[s.state]}</td><td>{money(s.balance)}</td><td><button disabled={busy} onClick={()=>open(s.id).catch(e=>setError(String(e)))}>Abrir turno {s.id}</button></td></tr>)}</tbody></table></div>{!rows.count&&<p>No hay turnos en este alcance. Dirección puede seleccionar un servicio y asignar el primer responsable.</p>}<button disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>Anterior</button> Página {page} <button disabled={page*50>=rows.count||busy} onClick={()=>setPage(p=>p+1)}>Siguiente</button></section>
 {selected&&<section className="panel" aria-label="Detalle de caja"><h2>{selected.label} · {selected.service_name}</h2><p>Responsable: {selected.responsible_name} · Asignó: {selected.assigned_by} · {states[selected.state]}</p><p>Fondo inicial: {money(selected.opening)} · Efectivo esperado: {money(selected.balance)}</p>
 {selected.state==="closed"&&<p>Arqueo: {money(selected.counted)} · Esperado al cierre: {money(selected.expected)} · Diferencia: {money(selected.difference)}. {selected.close_reason}</p>}
 {selected.state==="cancelled"&&<p>Motivo: {selected.close_reason}</p>}
 {selected.can_operate&&selected.state==="planned"&&<form onSubmit={e=>submit(e,"open")}><fieldset disabled={busy}><h3>Apertura</h3><label>Fondo inicial contado<input name="amount" type="number" min="0" max="9999999999.99" step="0.01" required/></label><button>Abrir caja</button></fieldset></form>}
 {selected.can_operate&&selected.state==="open"&&<><form onSubmit={e=>submit(e,"movement")} onChange={()=>{movementKey.current="";}}><fieldset disabled={busy}><h3>Registrar movimiento</h3><label>Tipo<select aria-label="Tipo" value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Importe neto en efectivo<input name="amount" type="number" min="0.01" max="9999999999.99" step="0.01" required/></label><label>Concepto / motivo<input name="concept" maxLength={240} required/></label><label>Referencia administrativa (opcional)<input name="reference" maxLength={100}/></label>{kind==="refund"&&<label>Número del cobro original (parte numérica de CAJ)<input name="related" type="number" min="1" required/></label>}<p>Registra el importe del servicio después de dar cambio. Usa una referencia de atención, sin diagnósticos. Los retiros deben indicar quién recibe el efectivo.</p><button>Guardar movimiento</button></fieldset></form><details><summary>Cerrar turno y realizar arqueo</summary><form onSubmit={e=>submit(e,"close")}><fieldset disabled={busy}><label>Efectivo contado al cierre<input name="amount" type="number" min="0" max="9999999999.99" step="0.01" required/></label><label>Observaciones / explicación de diferencias<textarea name="reason" maxLength={2000}/></label><p>El cierre es definitivo. El efectivo contado queda documentado; una entrega debe registrarse como retiro antes del cierre. El siguiente responsable contará y registrará su propio fondo inicial.</p><button>Cerrar turno definitivamente</button></fieldset></form></details></>}
 {selected.can_manage&&selected.state==="planned"&&<details><summary>Cancelar turno sin abrir</summary><form onSubmit={e=>submit(e,"cancel")}><fieldset disabled={busy}><label>Motivo<textarea name="reason" maxLength={2000} required/></label><button>Cancelar turno</button></fieldset></form></details>}
 <h3>Movimientos · {movements.count}</h3><p>Registro interno de efectivo; no es un comprobante fiscal. No se editan ni eliminan movimientos registrados.</p><div className="cash-scroll"><table><thead><tr><th>Folio / fecha</th><th>Movimiento</th><th>Importe</th><th>Concepto / referencia</th><th>Registró</th></tr></thead><tbody>{movements.results.map(m=><tr key={m.id}><td>{m.folio}<small>{date(m.created_at)}</small></td><td>{kinds[m.kind]}{m.related&&<small>Cobro original: CAJ-{String(m.related).padStart(8,"0")}</small>}</td><td>{money(m.amount)}</td><td>{m.concept}<small>{m.reference}</small></td><td>{m.actor}</td></tr>)}</tbody></table></div><button disabled={mpage===1||busy} onClick={()=>open(selected.id,mpage-1).catch(e=>setError(String(e)))}>Movimientos anteriores</button> Página {mpage} <button disabled={mpage*50>=movements.count||busy} onClick={()=>open(selected.id,mpage+1).catch(e=>setError(String(e)))}>Más movimientos</button>
 </section>}</main></>;
}
