# Generated by Django 5.2.17 on 2026-09-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='etag',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
