# Generated by Django 5.2.17 on 2026-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_etag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcerecord',
            name='section',
            field=models.TextField(),
        ),
    ]
