# Generated by Django 5.2.17 on 2026-09-23 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sourcerecord_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireinstance',
            name='etag',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='rationale',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='revocation_reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='revoked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='revoked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='etag',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GovernanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=200)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='HelpRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='help_revisions', to='core.questionnaireinstance')),
            ],
        ),
        migrations.CreateModel(
            name='HelpReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'approved'), ('returned', 'returned')], max_length=20)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='core.helprevision')),
            ],
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='help_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.helprevision'),
        ),
        migrations.AddField(
            model_name='questionnaireinstance',
            name='published_help',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.helprevision'),
        ),
        migrations.CreateModel(
            name='InstitutionMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.importbatch')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'batch'), name='catalog_access_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='helprevision',
            constraint=models.UniqueConstraint(fields=('instance', 'number'), name='service_help_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='institutionmandate',
            constraint=models.CheckConstraint(condition=models.Q(('starts__lte', models.F('ends'))), name='mandate_dates'),
        ),
        migrations.AddConstraint(
            model_name='institutionmandate',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('approved_by')), _negated=True), name='mandate_four_eyes'),
        ),
        migrations.AddConstraint(
            model_name='institutionmember',
            constraint=models.UniqueConstraint(fields=('institution', 'user'), name='institution_member_unique'),
        ),
    ]
