# Generated by Django 5.2.17 on 2026-09-23 20:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_preserve_published_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helprevision',
            name='origin',
            field=models.CharField(default='manual', max_length=40),
        ),
        migrations.AddField(
            model_name='helprevision',
            name='proposal_digest',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.CreateModel(
            name='ClarificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('due', models.DateField()),
                ('client_key', models.UUIDField()),
                ('state', models.CharField(default='open', max_length=20)),
                ('etag', models.PositiveIntegerField(default=0)),
                ('resolution', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.answerrevision')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('help_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.helprevision')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.questionnaireinstance')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClarificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('client_key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='core.clarificationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='HelpSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='core.helprevision')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sourcerecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clarificationrequest',
            constraint=models.UniqueConstraint(fields=('opened_by', 'client_key'), name='consultation_request_key'),
        ),
        migrations.AddConstraint(
            model_name='clarificationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('opened_by', models.F('assigned_to')), _negated=True), name='consultation_distinct_people'),
        ),
        migrations.AddConstraint(
            model_name='clarificationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('due__gte', datetime.date(2026, 10, 1))), name='consultation_plan_start'),
        ),
        migrations.AddConstraint(
            model_name='clarificationmessage',
            constraint=models.UniqueConstraint(fields=('request', 'author', 'client_key'), name='consultation_message_key'),
        ),
        migrations.AddConstraint(
            model_name='helpsourcelink',
            constraint=models.UniqueConstraint(fields=('revision', 'source'), name='help_source_unique'),
        ),
    ]
