# Generated by Django 5.2.17 on 2026-09-24 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_helprevision_origin_helprevision_proposal_digest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencedocument',
            name='etag',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='format',
            field=models.CharField(default='txt', max_length=10),
        ),
        migrations.CreateModel(
            name='EvidenceExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('token', models.UUIDField(null=True)),
                ('leased_until', models.DateTimeField(null=True)),
                ('error', models.CharField(default='', max_length=80)),
                ('extractor', models.CharField(default='text-csv-v1', max_length=40)),
                ('finished_at', models.DateTimeField(null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='extraction', to='core.evidencedocument')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=20)),
                ('rationale', models.TextField()),
                ('valid_until', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.evidencedocument')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('locator', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('cells', models.JSONField(null=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fragments', to='core.evidenceextraction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('extraction', 'ordinal'), name='evidence_fragment_ordinal')],
            },
        ),
    ]
