# Generated by Django 5.2.17 on 2026-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_evidencedocument_etag_evidencedocument_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencedocument',
            name='scanned_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='security_state',
            field=models.CharField(default='not_scanned', max_length=20),
        ),
    ]
