# Generated by Django 5.2.17 on 2026-09-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evidencedocument_scanned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefragment',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='evidencefragment',
            name='method',
            field=models.CharField(default='literal', max_length=20),
        ),
        migrations.AddField(
            model_name='evidencereview',
            name='ocr_checked',
            field=models.BooleanField(default=False),
        ),
    ]
