# Generated by Django 5.2.17 on 2026-09-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_evidencefragment_confidence_evidencefragment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencedocument',
            name='scan_required',
            field=models.BooleanField(default=False),
        ),
    ]
