# Generated by Django 5.2.17 on 2026-09-24 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_evidencedocument_scan_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFragmentRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=30)),
                ('rationale', models.TextField()),
                ('expires', models.DateField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.evidencefragment')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIServicePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_cost_limit', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('providers', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=False)),
                ('monthly_calls', models.PositiveIntegerField(default=0)),
                ('monthly_tokens', models.PositiveIntegerField(default=0)),
                ('rationale', models.TextField()),
                ('etag', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('estimated_cost', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('rate_snapshot', models.JSONField(default=dict)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(default='', max_length=120)),
                ('prompt_version', models.CharField(default='salud-assistant-1', max_length=40)),
                ('client_key', models.UUIDField()),
                ('answer_etag', models.PositiveIntegerField()),
                ('references', models.JSONField(default=list)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('error', models.CharField(default='', max_length=60)),
                ('result', models.JSONField(null=True)),
                ('reserved_tokens', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.answerrevision')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.questionnaireinstance')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('requested_by', 'client_key'), name='ai_request_key')],
            },
        ),
    ]
