# Generated by Django 5.2.17 on 2026-09-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aifragmentrelease_aiservicepolicy_airequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiservicepolicy',
            name='monthly_user_calls',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
