# Generated by Django 5.2.17 on 2026-09-24 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aiservicepolicy_monthly_user_calls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etag', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('nature', models.CharField(max_length=30)),
                ('numeral', models.CharField(blank=True, max_length=160)),
                ('consulted_version', models.CharField(blank=True, max_length=200)),
                ('official_url', models.URLField(blank=True, max_length=1000)),
                ('consulted_on', models.DateField(null=True)),
                ('validity', models.CharField(default='pending', max_length=20)),
                ('applicability', models.CharField(default='pending', max_length=20)),
                ('applicability_reason', models.TextField()),
                ('obligation', models.TextField()),
                ('link_reason', models.TextField()),
                ('next_review', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.answerrevision')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sourcerecord')),
                ('evidence', models.ManyToManyField(to='core.evidencedocument')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.complianceprocess')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.questionnaireinstance')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='core.compliancerecord')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.TextField()),
                ('expected', models.TextField()),
                ('observed', models.TextField()),
                ('result', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='core.compliancerevision')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=20)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.compliancerevision')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.compliancetest')),
            ],
        ),
        migrations.CreateModel(
            name='NormativeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('subject', models.TextField()),
                ('scope_text', models.TextField()),
                ('links', models.JSONField(default=list)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.sourcerecord')),
            ],
        ),
        migrations.AddField(
            model_name='compliancerevision',
            name='norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.normativeentry'),
        ),
        migrations.AddConstraint(
            model_name='complianceprocess',
            constraint=models.UniqueConstraint(fields=('service', 'name'), name='compliance_process_service_name'),
        ),
        migrations.AddConstraint(
            model_name='compliancerevision',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='compliance_revision_version'),
        ),
    ]
