# Generated by Django 5.2.17 on 2026-09-24 16:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_complianceprocess_compliancerecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='task_etag',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='acceptance_criteria',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='blocked_since',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='etag',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BaselineChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_etag', models.PositiveIntegerField()),
                ('proposal', models.JSONField()),
                ('previous', models.JSONField()),
                ('rationale', models.TextField()),
                ('state', models.CharField(default='pending', max_length=20)),
                ('review_reason', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_changes', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('note', models.TextField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etag', models.PositiveIntegerField(default=0)),
                ('weekdays', models.JSONField(default=list)),
                ('holidays', models.JSONField(default=list)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('rationale', models.TextField(default='')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='core.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependencies', to='core.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'predecessor'), name='task_dependency_unique'), models.CheckConstraint(condition=models.Q(('task', models.F('predecessor')), _negated=True), name='task_dependency_not_self')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('minutes', models.PositiveIntegerField()),
                ('note', models.TextField()),
                ('client_key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='core.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'client_key'), name='time_entry_key'), models.CheckConstraint(condition=models.Q(('minutes__gt', 0), ('minutes__lte', 1440)), name='time_entry_minutes'), models.CheckConstraint(condition=models.Q(('day__gte', datetime.date(2026, 10, 1))), name='time_entry_plan_start')],
            },
        ),
        migrations.CreateModel(
            name='WorkCalendarRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('weekdays', models.JSONField()),
                ('holidays', models.JSONField()),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='core.workplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'version'), name='work_calendar_version')],
            },
        ),
    ]
