# Generated by Django 5.2.17 on 2026-09-24 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_outboxevent_recipient_outboxevent_task_etag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField(default='')),
                ('enabled', models.BooleanField(default=False)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('last_step', models.BigIntegerField(default=-1)),
                ('recovery_hashes', models.JSONField(default=list)),
                ('pending_secret', models.TextField(default='')),
                ('pending_nonce', models.CharField(default='', max_length=64)),
                ('pending_until', models.DateTimeField(null=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
