# Generated by Django 5.2.17 on 2026-09-24 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mfadevice_securityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_etag', models.PositiveIntegerField()),
                ('etag', models.PositiveIntegerField(default=0)),
                ('items', models.JSONField(default=list)),
                ('help_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.helprevision')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.questionnaireinstance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('client_key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=30)),
                ('snapshot', models.JSONField()),
                ('answer_etag', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.answerrevision')),
                ('help_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.helprevision')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turns', to='core.interview')),
            ],
        ),
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.UniqueConstraint(fields=('instance', 'owner'), name='interview_owner_instance'),
        ),
        migrations.AddConstraint(
            model_name='interviewturn',
            constraint=models.UniqueConstraint(fields=('interview', 'client_key'), name='interview_retry_key'),
        ),
        migrations.AddConstraint(
            model_name='interviewturn',
            constraint=models.UniqueConstraint(fields=('interview', 'version'), name='interview_turn_version'),
        ),
    ]
