# Generated by Django 5.2.17 on 2026-09-25 13:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_interview_interviewturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='action',
            field=models.CharField(choices=[('suggest', 'suggest'), ('explain', 'explain'), ('interview', 'interview'), ('extract', 'extract')], default='suggest', max_length=20),
        ),
        migrations.AddField(
            model_name='aiservicepolicy',
            name='actions',
            field=models.JSONField(default=core.models.default_ai_actions),
        ),
    ]
