# Generated by Django 5.2.17 on 2026-09-25 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ai_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='action',
            field=models.CharField(choices=[('suggest', 'suggest'), ('explain', 'explain'), ('interview', 'interview'), ('extract', 'extract'), ('review', 'review')], default='suggest', max_length=20),
        ),
        migrations.CreateModel(
            name='AIAnswerRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_etag', models.PositiveIntegerField()),
                ('content_sha256', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=30)),
                ('rationale', models.TextField()),
                ('expires', models.DateField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.answerrevision')),
            ],
        ),
        migrations.AddField(
            model_name='airequest',
            name='answer_release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.aianswerrelease'),
        ),
    ]
