# Generated by Django 5.2.17 on 2026-09-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ai_answer_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='action',
            field=models.CharField(choices=[('suggest', 'suggest'), ('explain', 'explain'), ('interview', 'interview'), ('extract', 'extract'), ('review', 'review'), ('contradictions', 'contradictions')], default='suggest', max_length=20),
        ),
    ]
