# Generated by Django 5.2.17 on 2026-09-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ai_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianswerrelease',
            name='purpose',
            field=models.CharField(choices=[('review', 'review'), ('interview', 'interview')], default='review', max_length=20),
        ),
    ]
