# Generated by Django 5.2.17 on 2026-09-25 14:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ai_memory_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_snapshot', models.JSONField(default=dict)),
                ('title', models.CharField(max_length=250)),
                ('question', models.TextField()),
                ('alternatives', models.TextField()),
                ('due', models.DateField()),
                ('state', models.CharField(default='pending', max_length=20)),
                ('etag', models.PositiveIntegerField(default=1)),
                ('resolution', models.TextField(default='')),
                ('resolved_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.decision')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(('due__gte', datetime.date(2026, 10, 1))), name='decision_plan_start'),
        ),
        migrations.AddConstraint(
            model_name='decisionevent',
            constraint=models.UniqueConstraint(fields=('service', 'actor', 'client_key'), name='decision_operation_key'),
        ),
        migrations.AddConstraint(
            model_name='decisionevent',
            constraint=models.UniqueConstraint(fields=('decision', 'version'), name='decision_event_version'),
        ),
    ]
