# Generated by Django 5.2.17 on 2026-09-25 15:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_decision_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('etag', models.PositiveIntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('unavailable_minutes', models.PositiveIntegerField(default=0)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapacityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('expected_etag', models.PositiveIntegerField()),
                ('proposal', models.JSONField()),
                ('previous', models.JSONField()),
                ('rationale', models.TextField()),
                ('state', models.CharField(default='pending', max_length=20)),
                ('review_reason', models.TextField(default='')),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='core.capacityday')),
            ],
        ),
        migrations.CreateModel(
            name='CapacityAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.capacityday')),
            ],
        ),
        migrations.AddConstraint(
            model_name='capacityday',
            constraint=models.UniqueConstraint(fields=('institution', 'person', 'day'), name='capacity_person_day'),
        ),
        migrations.AddConstraint(
            model_name='capacityday',
            constraint=models.CheckConstraint(condition=models.Q(('minutes__lte', 1440), ('unavailable_minutes__lte', models.F('minutes')), ('day__gte', datetime.date(2026, 10, 1))), name='capacity_day_bounds'),
        ),
        migrations.AddConstraint(
            model_name='capacitychange',
            constraint=models.UniqueConstraint(fields=('institution', 'requested_by', 'client_key'), name='capacity_change_key'),
        ),
        migrations.AddConstraint(
            model_name='capacityallocation',
            constraint=models.UniqueConstraint(fields=('capacity', 'service'), name='capacity_service_unique'),
        ),
        migrations.AddConstraint(
            model_name='capacityallocation',
            constraint=models.CheckConstraint(condition=models.Q(('minutes__gt', 0), ('minutes__lte', 1440)), name='capacity_allocation_bounds'),
        ),
    ]
