# Generated by Django 5.2.17 on 2026-09-28 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_capacity_planning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.UUIDField()),
                ('start', models.DateField()),
                ('content', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('rationale', models.TextField(default='')),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'created_by', 'client_key'), name='unique_saved_report_retry')],
            },
        ),
    ]
