# Generated by Django 5.2.17 on 2026-09-28 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_saved_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField()),
                ('expected_state', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='core.savedreport')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposition', to='core.savedreport')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('report', models.F('replacement')), _negated=True), name='report_cannot_replace_itself')],
            },
        ),
    ]
