# Generated by Django 5.2.17 on 2026-09-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_decision_notice_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='substitutes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitutions', to='core.roleassignment'),
        ),
    ]
