# Generated by Django 5.2.17 on 2026-09-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_assignment_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='coverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_notices', to='core.roleassignment'),
        ),
    ]
