# Generated by Django 5.2.17 on 2026-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_task_coverage_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionnoticereceipt',
            name='coverage_ids',
            field=models.JSONField(default=list),
        ),
    ]
