# Generated by Django 5.2.17 on 2026-09-28 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_receipt_coverage_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('first_period', models.DateField()),
                ('rationale', models.TextField()),
                ('last_checked', models.DateTimeField(null=True)),
                ('last_status', models.CharField(default='not_run', max_length=30)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('schedule_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.savedreport')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='core.reportschedule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule', 'period'), name='unique_scheduled_report_period')],
            },
        ),
    ]
