# Generated by Django 5.2.17 on 2026-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_report_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreportrun',
            name='generation_mode',
            field=models.CharField(default='scheduled', max_length=16),
        ),
        migrations.AddField(
            model_name='scheduledreportrun',
            name='rationale',
            field=models.TextField(default=''),
        ),
    ]
