# Generated by Django 5.2.17 on 2026-09-28 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_report_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField()),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.timeentry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entry', 'version'), name='time_correction_version'), models.CheckConstraint(condition=models.Q(('minutes__lte', 1440), ('version__gt', 0)), name='time_correction_bounds')],
            },
        ),
    ]
