# Generated by Django 5.2.17 on 2026-09-28 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_time_corrections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='budget_bucket',
            field=models.CharField(default='base', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='reservation_plan',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='PlanningPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforced', models.BooleanField(default=False)),
                ('etag', models.PositiveIntegerField(default=0)),
                ('base_minutes', models.PositiveIntegerField(default=0)),
                ('reserve_minutes', models.PositiveIntegerField(default=0)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
            ],
        ),
        migrations.CreateModel(
            name='TaskReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('minutes', models.PositiveIntegerField()),
                ('capacity_version', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'person', 'day'), name='task_person_day_reservation'), models.CheckConstraint(condition=models.Q(('minutes__gt', 0), ('minutes__lte', 1440)), name='task_reservation_minutes')],
            },
        ),
    ]
