# Generated by Django 5.2.17 on 2026-09-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_planning_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='budget_bucket',
            field=models.CharField(default='base', max_length=10),
        ),
    ]
