# Generated by Django 5.2.17 on 2026-09-28 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_time_budget_bucket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helprevision',
            name='question_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.questionversion'),
        ),
        migrations.CreateModel(
            name='QuestionSourceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_etag', models.PositiveIntegerField()),
                ('rationale', models.TextField()),
                ('review_reason', models.TextField(default='')),
                ('state', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_changes', to='core.questionnaireinstance')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.questionversion')),
                ('source_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.questionversion')),
            ],
        ),
    ]
