# Generated by Django 5.2.17 on 2026-09-29 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_question_source_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeTimeCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.UUIDField()),
                ('expected_version', models.PositiveIntegerField()),
                ('previous_minutes', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField()),
                ('rationale', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=12)),
                ('review_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('correction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrative_request', to='core.timecorrection')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_requests', to='core.timeentry')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entry', 'requested_by', 'client_key'), name='admin_time_request_key'), models.CheckConstraint(condition=models.Q(('minutes__lte', 1440), ('previous_minutes__lte', 1440)), name='admin_time_request_bounds')],
            },
        ),
    ]
