# Generated by Django 5.2.17 on 2026-09-29 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_administrative_time_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mfadevice',
            name='recovery_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='recovery_session_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='ExceptionalMFARecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.UUIDField()),
                ('expected_generation', models.PositiveIntegerField()),
                ('requester_generation', models.PositiveIntegerField()),
                ('reviewer_generation', models.PositiveIntegerField(null=True)),
                ('approved_generation', models.PositiveIntegerField(null=True)),
                ('rationale', models.TextField()),
                ('verification_reference', models.CharField(max_length=250)),
                ('review_reason', models.TextField(blank=True)),
                ('review_reference', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('consumed', 'Código canjeado'), ('completed', 'Completada'), ('revoked', 'Revocada')], default='pending', max_length=12)),
                ('token_hash', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('requested_by', 'client_key'), name='exceptional_mfa_request_key')],
            },
        ),
    ]
