# Generated by Django 5.2.17 on 2026-09-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_patient_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=160)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=80)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('target_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='core.academiccycle')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_placements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.UUIDField()),
                ('title', models.CharField(max_length=200)),
                ('performed_on', models.DateField()),
                ('minutes', models.PositiveIntegerField()),
                ('competency', models.CharField(max_length=300)),
                ('evidence_reference', models.CharField(max_length=500)),
                ('activity_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Por revisar'), ('returned', 'Devuelta'), ('validated', 'Validada'), ('void', 'Anulada')], default='submitted', max_length=20)),
                ('etag', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practices', to='core.academicplacement')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPracticeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=30)),
                ('rationale', models.TextField(blank=True)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.academicpractice')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=60)),
                ('program', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='academic_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='academicplacement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='core.academicstudent'),
        ),
        migrations.AddConstraint(
            model_name='academiccycle',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='academic_cycle_code'),
        ),
        migrations.AddConstraint(
            model_name='academiccycle',
            constraint=models.CheckConstraint(condition=models.Q(('starts__lte', models.F('ends'))), name='academic_cycle_dates'),
        ),
        migrations.AddConstraint(
            model_name='academicpractice',
            constraint=models.UniqueConstraint(fields=('placement', 'client_key'), name='academic_practice_retry'),
        ),
        migrations.AddConstraint(
            model_name='academicpractice',
            constraint=models.CheckConstraint(condition=models.Q(('minutes__gt', 0), ('minutes__lte', 1440)), name='academic_practice_minutes'),
        ),
        migrations.AddConstraint(
            model_name='academicpracticeevent',
            constraint=models.UniqueConstraint(fields=('practice', 'version'), name='academic_practice_event_version'),
        ),
        migrations.AddConstraint(
            model_name='academicstudent',
            constraint=models.UniqueConstraint(fields=('institution', 'enrollment'), name='academic_student_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='academicplacement',
            constraint=models.CheckConstraint(condition=models.Q(('starts__lte', models.F('ends'))), name='academic_placement_dates'),
        ),
        migrations.AddConstraint(
            model_name='academicplacement',
            constraint=models.CheckConstraint(condition=models.Q(('target_minutes__isnull', True), ('target_minutes__gt', 0), _connector='OR'), name='academic_target_positive'),
        ),
    ]
