# Generated by Django 5.2.17 on 2026-09-30 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_academic_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccycle',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='academiccycle',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AcademicCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=160)),
                ('code', models.CharField(max_length=60)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencies', to='core.academiccycle')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCycleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('source_revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('client_key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='core.academiccycle')),
            ],
        ),
        migrations.AddField(
            model_name='academiccycle',
            name='closed_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.academiccyclereport'),
        ),
        migrations.CreateModel(
            name='AcademicRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('criterion', models.TextField()),
                ('levels', models.JSONField()),
                ('required_level', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=True)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='core.academiccompetency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('rationale', models.TextField()),
                ('evidence', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academiccompetency')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='core.academicplacement')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academicrubric')),
            ],
        ),
        migrations.AddConstraint(
            model_name='academiccompetency',
            constraint=models.UniqueConstraint(fields=('cycle', 'service', 'program', 'code'), name='academic_competency_code'),
        ),
        migrations.AddConstraint(
            model_name='academiccyclereport',
            constraint=models.UniqueConstraint(fields=('cycle', 'sequence'), name='academic_cycle_report_sequence'),
        ),
        migrations.AddConstraint(
            model_name='academiccyclereport',
            constraint=models.UniqueConstraint(fields=('cycle', 'client_key'), name='academic_report_retry'),
        ),
        migrations.AddConstraint(
            model_name='academicrubric',
            constraint=models.UniqueConstraint(fields=('competency', 'version'), name='academic_rubric_version'),
        ),
        migrations.AddConstraint(
            model_name='academicevaluation',
            constraint=models.UniqueConstraint(fields=('placement', 'competency', 'version'), name='academic_evaluation_version'),
        ),
    ]
