# Generated by Django 5.2.17 on 2026-09-30 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_academic_assessment_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAcademicGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('rationale', models.TextField()),
                ('revoked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('rationale', models.TextField()),
                ('revoked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='academiccycle',
            name='academic_cycle_code',
        ),
        migrations.AddField(
            model_name='school',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution'),
        ),
        migrations.AddField(
            model_name='academiccycle',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
        ),
        migrations.AddField(
            model_name='academicstudent',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
        ),
        migrations.AddField(
            model_name='service',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
        ),
        migrations.AddConstraint(
            model_name='academiccycle',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', True)), fields=('institution', 'code'), name='academic_legacy_cycle_code'),
        ),
        migrations.AddConstraint(
            model_name='academiccycle',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', False)), fields=('school', 'code'), name='academic_school_cycle_code'),
        ),
        migrations.AddField(
            model_name='schoolacademicgrant',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolacademicgrant',
            name='reader_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_read_access', to='core.school'),
        ),
        migrations.AddField(
            model_name='schoolacademicgrant',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_grants', to='core.school'),
        ),
        migrations.AddField(
            model_name='schoolmandate',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolmandate',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.school'),
        ),
        migrations.AddField(
            model_name='schoolmandate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolmember',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.school'),
        ),
        migrations.AddField(
            model_name='schoolmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='school_code'),
        ),
        migrations.AddConstraint(
            model_name='schoolacademicgrant',
            constraint=models.CheckConstraint(condition=models.Q(('starts__lte', models.F('ends'))), name='school_grant_dates'),
        ),
        migrations.AddConstraint(
            model_name='schoolacademicgrant',
            constraint=models.CheckConstraint(condition=models.Q(('school', models.F('reader_school')), _negated=True), name='school_grant_distinct'),
        ),
        migrations.AddConstraint(
            model_name='schoolmandate',
            constraint=models.CheckConstraint(condition=models.Q(('starts__lte', models.F('ends'))), name='school_mandate_dates'),
        ),
        migrations.AddConstraint(
            model_name='schoolmandate',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('approved_by')), _negated=True), name='school_mandate_four_eyes'),
        ),
        migrations.AddConstraint(
            model_name='schoolmember',
            constraint=models.UniqueConstraint(fields=('school', 'user'), name='school_member'),
        ),
    ]
