# Generated by Django 5.2.17 on 2026-09-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_school_boundaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('public_name', models.CharField(max_length=180)),
                ('area', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField()),
                ('audience', models.CharField(choices=[('general', 'Público en general'), ('university', 'Comunidad universitaria')], max_length=20)),
                ('schedule', models.JSONField(default=list)),
                ('contacts', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('location_note', models.TextField(blank=True)),
                ('classification_basis', models.TextField(blank=True)),
                ('source_url', models.URLField()),
                ('source_checked_on', models.DateField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('published', models.BooleanField(default=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='institutional_information', to='core.service')),
            ],
        ),
    ]
