# Generated by Django 5.2.17 on 2026-10-01 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_disable_school_sharing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('state', models.CharField(choices=[('planned', 'Programado'), ('open', 'Abierto'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado')], default='planned', max_length=12)),
                ('opening', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('counted', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('expected', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('client_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('collection', 'Cobro'), ('fund_in', 'Ingreso de fondo'), ('withdrawal', 'Retiro / entrega'), ('refund', 'Devolución')], max_length=16)),
                ('method', models.CharField(default='cash', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concept', models.CharField(max_length=240)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_key', models.UUIDField(unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cashmovement')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.cashshift')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.CheckConstraint(condition=models.Q(('starts__lt', models.F('ends'))), name='cash_shift_dates'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'open')), fields=('service',), name='cash_one_open_service'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.CheckConstraint(condition=models.Q(('opening__isnull', True), ('opening__gte', 0), _connector='OR'), name='cash_opening_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.CheckConstraint(condition=models.Q(('counted__isnull', True), ('counted__gte', 0), _connector='OR'), name='cash_counted_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('method', 'cash')), name='cash_only_method'),
        ),
    ]
