"use client";
import {useState} from 'react';
import {api} from '../../lib/api';
type Distribution={next_people_after:number|null;next_deliveries_before:number|null;eligible_recipients:{user_id:number;user__username:string}[];deliveries:{id:number;recipient_id:number;created_at:string;acknowledged_at:string|null}[]};
export default function ReportDistribution({report,hash}:{report:number;hash:string}){
 const [data,setData]=useState<Distribution>(),[recipients,setRecipients]=useState<number[]>([]),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(section?:'people'|'deliveries'){
  const cursor=section==='people'?data?.next_people_after:data?.next_deliveries_before;
  const query=section&&cursor?`?${section==='people'?'people_after':'deliveries_before'}=${cursor}`:'';
  const page=await api<Distribution>(`reports/saved/${report}/distribution/${query}`);
  setData(previous=>!section||!previous?page:section==='people'?{...previous,eligible_recipients:[...previous.eligible_recipients,...page.eligible_recipients.filter(row=>!previous.eligible_recipients.some(old=>old.user_id===row.user_id))],next_people_after:page.next_people_after}:{...previous,deliveries:[...previous.deliveries,...page.deliveries.filter(row=>!previous.deliveries.some(old=>old.id===row.id))],next_deliveries_before:page.next_deliveries_before});
 }
 async function run(fn:()=>Promise<void>){setBusy(true);setNotice('');try{await fn();}catch(e){setNotice((e as Error).message);setData(undefined);setRecipients([]);}finally{setBusy(false);}}
 return <section aria-label="Distribución interna"><h4>Distribución y lecturas</h4><p>Dirección puede distribuir esta versión aprobada a personas con acceso vigente. Se coloca en su bandeja interna; no se envía correo. La entrega no equivale a lectura.</p><button disabled={busy} onClick={()=>void run(async()=>{setRecipients([]);await load();})}>Consultar destinatarios y lecturas (Dirección)</button><p role="status">{notice}</p>{data&&<><form onSubmit={e=>{e.preventDefault();void run(async()=>{const result=await api<{created:number;already_delivered:number}>(`reports/saved/${report}/distribution/`,'POST',{content_hash:hash,recipients,rationale:reason});setRecipients([]);await load();setNotice(`Entregas nuevas: ${result.created}. Ya entregadas: ${result.already_delivered}.`);});}}><fieldset disabled={busy}><legend>Destinatarios seleccionados explícitamente</legend>{data.eligible_recipients.map(u=><label key={u.user_id}><input type="checkbox" checked={recipients.includes(u.user_id)} disabled={!recipients.includes(u.user_id)&&recipients.length>=100} onChange={e=>setRecipients(e.target.checked?[...recipients,u.user_id]:recipients.filter(id=>id!==u.user_id))}/>{u.user__username}</label>)}</fieldset>{data.next_people_after!==null&&<button type="button" disabled={busy} onClick={()=>void run(()=>load('people'))}>Cargar más destinatarios</button>}<p>Seleccionados: {recipients.length} de un máximo de 100 por envío.</p><label>Motivo de distribución<textarea required maxLength={3000} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()||recipients.length===0}>Distribuir en bandeja interna</button></form><h4>Entregas registradas</h4>{data.deliveries.length?<ul>{data.deliveries.map(d=><li key={d.id}>Persona {d.recipient_id}: {d.acknowledged_at?`Lectura confirmada el ${new Date(d.acknowledged_at).toLocaleString('es-MX')}`:'Entregado; lectura pendiente'}</li>)}</ul>:<p>Sin entregas registradas.</p>}{data.next_deliveries_before!==null&&<button disabled={busy} onClick={()=>void run(()=>load('deliveries'))}>Cargar más entregas registradas</button>}</>}</section>;
}
