"use client";
import { useEffect, useRef, useState } from 'react';
import { api, setCsrf } from '../../lib/api';
import WeeklyContent, { Report } from './WeeklyContent';
import ReportReplacementPicker,{ReplacementReport} from './ReportReplacementPicker';
import ReportDistribution from './ReportDistribution';
type Saved = {id:number; start:string; state:string; content_hash:string; created_by_id:number; rationale:string; reviewed_by_id:number|null; content?:Report; generation?:{kind:string;rationale?:string;schedule_id?:number;schedule_version?:number}; availability:string; disposition:{replacement_id:number|null;actor_id:number;rationale:string;created_at:string}|null};
export default function SavedReports({service}:{service:string}) {
  const [rows,setRows]=useState<Saved[]>([]),[selected,setSelected]=useState<Saved>(),[start,setStart]=useState(''),[reason,setReason]=useState(''),[withdrawReason,setWithdrawReason]=useState(''),[replacement,setReplacement]=useState<ReplacementReport>(),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [pickerBusy,setPickerBusy]=useState(false);
  const [next,setNext]=useState<number|null>(null);
  type SavedPage={results:Saved[];next_before:number|null};
  const retry=useRef<{payload:string;key:string}|undefined>(undefined);
  const reload=async(before?:number)=>{const data=await api<SavedPage>(`reports/services/${service}/saved/${before?`?before=${before}`:''}`);setRows(old=>before?[...old,...data.results.filter(r=>!old.some(p=>p.id===r.id))]:data.results);setNext(data.next_before);};
  useEffect(()=>{let current=true;setBusy(true);setRows([]);setNext(null);setSelected(undefined);setNotice('');api<{csrf:string}>('session/').then(s=>{setCsrf(s.csrf);return api<SavedPage>(`reports/services/${service}/saved/`);}).then(data=>{if(current){setRows(data.results);setNext(data.next_before);}}).catch(e=>{if(current)setNotice(e.message);}).finally(()=>{if(current)setBusy(false);});return()=>{current=false;};},[service]);
  async function run(fn:()=>Promise<void>){setBusy(true);setNotice('');try{await fn();}catch(e){setNotice((e as Error).message);setRows([]);setNext(null);setSelected(undefined);setReplacement(undefined);}finally{setBusy(false);}}
  return <section aria-label="Informes conservados"><h2>Versiones conservadas y revisión</h2><p>Guardar genera una nueva consulta de los datos actuales y conserva su contenido fijo. Revise esa versión antes de aprobar. La aprobación no envía el informe ni acredita aceptación clínica.</p>
    <form onSubmit={e=>{e.preventDefault();void run(async()=>{const payload=JSON.stringify({service,start});if(retry.current?.payload!==payload)retry.current={payload,key:crypto.randomUUID()};const row=await api<Saved>(`reports/services/${service}/saved/`,'POST',{start,client_key:retry.current.key});setSelected(row);await reload();retry.current=undefined;});}}><label>Inicio de la versión a conservar<input required type="date" value={start} disabled={busy} onChange={e=>setStart(e.target.value)}/></label><button disabled={busy}>Generar y conservar versión</button></form>
    <button disabled={busy} onClick={()=>void run(()=>reload())}>Actualizar versiones</button><p role="status">{notice}</p>
    {rows.length ? <ul>{rows.map(r=><li key={r.id}>Informe {r.id} · {r.start} · {({pending:'Pendiente',approved:'Aprobado',rejected:'Rechazado'} as Record<string,string>)[r.state]}  · {r.availability==='withdrawn'?'Retirado':r.availability==='superseded'?'Sustituido':'Conservado'} <button disabled={busy} onClick={()=>void run(async()=>{setSelected(await api<Saved>(`reports/saved/${r.id}/`));setReason('');setReplacement(undefined);setWithdrawReason('');})}>Consultar versión {r.id}</button></li>)}</ul>:<p>No hay versiones conservadas.</p>}
    {next!==null&&<button disabled={busy} onClick={()=>void run(()=>reload(next))}>Cargar más versiones conservadas</button>}
    {selected && <article><h3>Versión conservada {selected.id}</h3>{selected.generation?.kind==='backfill' && <p>Borrador por recuperación explícita de semana omitida. Motivo: {selected.generation.rationale}. El estado refleja el momento de generación, no el cierre histórico.</p>}{selected.generation?.kind==='scheduled' && <p>Borrador generado automáticamente por programación {selected.generation.schedule_id}, versión {selected.generation.schedule_version}. La persona indicada autorizó su generación.</p>}<p>Estado: {({pending:'Pendiente',approved:'Aprobado',rejected:'Rechazado'} as Record<string,string>)[selected.state]}. Preparada por {selected.created_by_id}. Revisión: {selected.reviewed_by_id??'Pendiente'}.</p><p>{selected.rationale}</p><p>Huella del contenido: {selected.content_hash}</p>{selected.content && <WeeklyContent report={selected.content} service={service} saved />}<a href={`/api/v1/reports/saved/${selected.id}/`}>Exportar versión y resolución</a>
    {selected.state==='approved' && selected.availability==='retained' && <ReportDistribution key={selected.id} report={selected.id} hash={selected.content_hash} />}
    {selected.state==='pending' && selected.availability==='retained' && <form onSubmit={e=>e.preventDefault()}><p>La resolución requiere otra persona de Dirección con acceso vigente al servicio.</p><label>Fundamento de la revisión<textarea required value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label>{[true,false].map(approve=><button key={String(approve)} disabled={busy||!reason.trim()} onClick={()=>void run(async()=>{setSelected(await api<Saved>(`reports/saved/${selected.id}/`,'POST',{approve,rationale:reason,content_hash:selected.content_hash}));await reload();})}>{approve?'Aprobar versión':'Rechazar versión'}</button>)}</form>}
    {selected.disposition ? <aside aria-label="Retiro registrado"><h4>{selected.availability==='superseded'?'Informe sustituido':'Informe retirado'}</h4><p>{selected.disposition.rationale}</p><p>Registrado por {selected.disposition.actor_id} el {new Date(selected.disposition.created_at).toLocaleString('es-MX')}. Se conserva la resolución histórica.</p>{selected.disposition.replacement_id && <button disabled={busy} onClick={()=>void run(async()=>{setSelected(await api<Saved>(`reports/saved/${selected.disposition!.replacement_id}/`));setReplacement(undefined);setWithdrawReason('');})}>Consultar informe sustituto</button>}</aside> : <form onSubmit={e=>{e.preventDefault();void run(async()=>{const candidate=replacement;setSelected(await api<Saved>(`reports/saved/${selected.id}/disposition/`,'POST',{content_hash:selected.content_hash,expected_state:selected.state,replacement:candidate?.id??null,replacement_hash:candidate?.content_hash??null,rationale:withdrawReason}));await reload();});}}><h4>Retirar o sustituir informe</h4><p>El retiro es definitivo y conserva contenido y resolución. La persona autora puede retirar su borrador pendiente; los demás casos y las sustituciones requieren Dirección.</p><ReportReplacementPicker key={selected.id} service={service} start={selected.start} exclude={selected.id} value={replacement?.id??null} onChange={setReplacement} disabled={busy} onBusyChange={setPickerBusy}/><label>Fundamento del retiro o sustitución<textarea required disabled={busy} value={withdrawReason} onChange={e=>setWithdrawReason(e.target.value)}/></label><button disabled={busy||pickerBusy||!withdrawReason.trim()}>Registrar retiro o sustitución</button></form>}
    </article>}
  </section>;
}
